"""Add daily review scheduling fields

Revision ID: 1f42734f93e8
Revises: c4b4889a53a1
Create Date: 2025-09-03 19:43:58.737176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f42734f93e8'
down_revision: Union[str, None] = 'c4b4889a53a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_review_task_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('daily_review_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_review_time')
    op.drop_column('users', 'daily_review_task_id')
    # ### end Alembic commands ###
